services:
  - type: web
    name: api-shop
    runtime: java      # <--- Sửa dòng này
    plan: free
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: $PORT
      - key: SPRING_PROFILES_ACTIVE
        value: production