services:
  - type: web
    name: api-shop
    env: java
    runtime: openjdk-17   # <--- sửa lại như này
    plan: free
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: $PORT
