server:
  port: 8080
  servlet:
    context-path: /shop
spring:
  data:
    mongodb:
      uri: mongodb+srv://anhminh270622:BRWfOwC5DDQAhdrY@database-shop.n1utoec.mongodb.net/demo?retryWrites=true&w=majority&appName=database-shop
jwt:
  apiKeyToken: "D9LGeo6XIxglpGGsXZddTd8hW5W9Y80hMxbDnPhlFJToI113fVE08WC0I0lM4Btf"
debug: true